spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8080

upload.dir: D:\reserv\Spring\common\upload