spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root



  jpa:
    show-sql=true

upload.dir: E:\OnlineShop\rest\upload


logging:
  file:
    path: E:\OnlineShop\common\log
    name: springdemo.log



#spring.datasource.url=jdbc:mysql://localhost:3306/onlineshop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root

